version: "3.9"

services:
  demo-go:
    build:
      context: .
      dockerfile: Dockerfile
    image: vietquoc2408/demo-go-api:1.0.0
    container_name: demo-go-api
    restart: always
    ports:
      - "8080:8080"
    environment:
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=root
      - DB_NAME=demo_go
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - demo-go-network
      
  mysql:
    image: mysql:8.0
    container_name: mysql-go
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=demo_go
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - demo-go-network

networks:
  demo-go-network:
    driver: bridge

volumes:
  mysql_data:
